// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieProject.Models;

#nullable disable

namespace MovieProject.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    [Migration("20250908054135_CreateBuddyRequestsTable")]
    partial class CreateBuddyRequestsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieProject.Models.BuddyRequest", b =>
                {
                    b.Property<int>("BuddyRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuddyRequestId"));

                    b.Property<int>("FromUserId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAccepted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("ToUserId")
                        .HasColumnType("int");

                    b.HasKey("BuddyRequestId");

                    b.HasIndex("FromUserId");

                    b.HasIndex("ToUserId");

                    b.ToTable("BuddyRequests");
                });

            modelBuilder.Entity("MovieProject.Models.Favorite", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("FavoriteId")
                        .HasName("PK__Favorite__CE74FAD5CBC2C350");

                    b.HasIndex("MovieId");

                    b.HasIndex(new[] { "UserId", "MovieId" }, "UQ__Favorite__A335E50CC2D1DBE1")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [MovieId] IS NOT NULL");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("MovieProject.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<string>("MovieGenre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("decimal(3, 1)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.HasKey("MovieId")
                        .HasName("PK__Movies__4BD2941A6A613929");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("MovieProject.Models.RecMovie", b =>
                {
                    b.Property<int>("RecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecId"));

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("RecId")
                        .HasName("PK__RecMovie__360414DF09D5D02D");

                    b.HasIndex("MovieId");

                    b.ToTable("RecMovies");
                });

            modelBuilder.Entity("MovieProject.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("bit");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("MovieProject.Models.TrendingMovie", b =>
                {
                    b.Property<int>("TrendingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrendingId"));

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TrendingScore")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("TrendingId")
                        .HasName("PK__Trending__987654321FEDCBA");

                    b.HasIndex("MovieId");

                    b.ToTable("TrendingMovies");
                });

            modelBuilder.Entity("MovieProject.Models.UpcomingMovie", b =>
                {
                    b.Property<int>("UpcomingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UpcomingId"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("text");

                    b.Property<string>("MovieGenre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MovieTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("TrailerUrl")
                        .HasColumnType("text");

                    b.HasKey("UpcomingId")
                        .HasName("PK__Upcoming__123456789ABCDEF");

                    b.ToTable("UpcomingMovies");
                });

            modelBuilder.Entity("MovieProject.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("user");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C7BD16D06");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E4846AC91D")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MovieProject.Models.WatchList", b =>
                {
                    b.Property<int>("WatchlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchlistId"));

                    b.Property<int?>("MovieId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WatchlistId")
                        .HasName("PK__WatchLis__48DE55CB1FAAC170");

                    b.HasIndex("MovieId");

                    b.HasIndex(new[] { "UserId", "MovieId" }, "UQ__WatchLis__A335E50C6D51D3E6")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL AND [MovieId] IS NOT NULL");

                    b.ToTable("WatchList", (string)null);
                });

            modelBuilder.Entity("MovieProject.Models.BuddyRequest", b =>
                {
                    b.HasOne("MovieProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieProject.Models.User", null)
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieProject.Models.Favorite", b =>
                {
                    b.HasOne("MovieProject.Models.Movie", "Movie")
                        .WithMany("Favorites")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK__Favorites__Movie__5AEE82B9");

                    b.HasOne("MovieProject.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__Favorites__UserI__59FA5E80");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieProject.Models.RecMovie", b =>
                {
                    b.HasOne("MovieProject.Models.Movie", "Movie")
                        .WithMany("RecMovies")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK__RecMovies__Movie__4D94879B");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieProject.Models.Review", b =>
                {
                    b.HasOne("MovieProject.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieProject.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieProject.Models.TrendingMovie", b =>
                {
                    b.HasOne("MovieProject.Models.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK__TrendingM__Movie__12345678");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieProject.Models.WatchList", b =>
                {
                    b.HasOne("MovieProject.Models.Movie", "Movie")
                        .WithMany("WatchLists")
                        .HasForeignKey("MovieId")
                        .HasConstraintName("FK__WatchList__Movie__5629CD9C");

                    b.HasOne("MovieProject.Models.User", "User")
                        .WithMany("WatchLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK__WatchList__UserI__5535A963");

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MovieProject.Models.Movie", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("RecMovies");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("MovieProject.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("WatchLists");
                });
#pragma warning restore 612, 618
        }
    }
}
